iqCP/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.profile_view, name='profile')
]

iqCP/iqCP/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cpanel/', include([
        url(r'^', include('dashboard.urls')),
        url(r'^promo/', include('promo.urls')),
        url(r'^auth/logout', auth_views.logout_then_login, name='iq-logout'),
        url(r'^auth', auth_views.login, name='iq-login'),
        url(r'^profile/', include('accounts.urls')),
        url(r'^users/', include('users.urls')),
        url(r'^events/', include('events.urls')),
    ])),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

iqCP/templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>


</body>
</html>

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lumino - Dashboard</title>

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
<link href="{% static 'css/styles.css' %}" rel="stylesheet">

<!--Icons-->
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

<!--[if lt IE 9]>
<script src="{% static 'js/html5shiv.js' %}"></script>
<script src="{% static 'js/respond.min.js' %}"></script>
<![endif]-->

<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"><span>IQ</span>Control Panel</a>
				<ul class="user-menu">
					<li class="dropdown pull-right">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg>{{user.first_name }}<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="{% url 'accounts:profile' %}"><span class="fa fa-user" aria-hidden="true"></span>Настройки</a></li>
							<li><a href="{% url 'iq-logout' %}"><span class="fa fa-sign-out" aria-hidden="true"></span>Выход</a></li>
						</ul>
					</li>
				</ul>
			</div>

		</div><!-- /.container-fluid -->
	</nav>
	{% block sidebar %}
	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<ul class="nav menu">
			<li {% if request.resolver_match.view_name == "promo:subscribers" %}
				class="active"
				{% endif %}>
				<a href="{% url 'promo:subscribers' %}">
					<span class="fa fa-user-plus"></span>
					Подписчики
				</a>
			</li>
			<li {% if request.resolver_match.view_name == "promo:promo_codes" or request.resolver_match.view_name == "promo:promo_code" %}
				class="active"
				{% endif %}>
				<a href="{% url 'promo:promo_codes' %}">
					<span class="fa fa-table"></span>
					Промокоды
				</a>
			</li>
			<li {% if request.resolver_match.view_name == "users:list" %}
				class="active"
				{% endif %}>
				<a href="{% url 'users:list' %}">
					<span class="fa fa-users"></span>
					Пользователи
				</a>
			</li>
			<li {% if request.resolver_match.view_name == "events:stat" %}
				class="active"
				{% endif %}>
				<a href="{% url 'events:stat' %}">
					<span class="fa fa-pie-chart"></span>
					Статистика событий
				</a>
			</li>
		</ul>

	</div><!--/.sidebar-->
	{% endblock sidebar %}

	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		{% block content %}
        {% endblock %}
	</div>	<!--/.main-->

	<script src="{% static 'js/chart.min.js' %}"></script>
	<script src="{% static 'js/chart-data.js' %}"></script>
	<script src="{% static 'js/easypiechart.js' %}"></script>
	<script src="{% static 'js/easypiechart-data.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script>
		$('#calendar').datepicker({
		});

		!function ($) {
		    $(document).on("click","ul.nav li.parent > a > span.icon", function(){
		        $(this).find('em:first').toggleClass("glyphicon-minus");
		    });
		    $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
		}(window.jQuery);

		$(window).on('resize', function () {
		  if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
		})
		$(window).on('resize', function () {
		  if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
		})
	</script>
</body>

</html>