iqCP/iqCP/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cpanel/', include([
        url(r'^', include('dashboard.urls')),
        url(r'^promo/', include('promo.urls')),
        url(r'^auth/logout', auth_views.logout_then_login, name='iq-logout'),
        url(r'^auth', auth_views.login, name='iq-login'),
        url(r'^profile/', include('accounts.urls')),
        url(r'^users/', include('users.urls')),
        url(r'^events/', include('events.urls')),
    ])),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

iqCP/promo/urls.py
from django.conf.urls import url

from . import views

app_name = 'promo'
urlpatterns = [
    url(r'^$', views.PromoCodesListView.as_view(), name='promo_codes'),
    url(r'^codes/', views.PromoCodesListView.as_view(), name='promo_codes'),
    url(r'code/(?P<pk>[0-9]+)/', views.PromoCodeDetailView.as_view(), name='promo_code'),
    url(r'code/delete/(?P<pk>[0-9]+)', views.PromoCodeDelete.as_view(), name='delete_promo'),
    url(r'invite(?:/code/(?P<promo_code>\w*))?(?:/name/(?P<first_name>[\w ]*))?(?:/email/(?P<email>.*))?$', views.invite_view, name='invite'),
    url(r'invite/subscriber/(?P<subscriber_id>[0-9]*)', views.invite_view, name='invite'),
    url(r'^subscribers/', views.SubscribersView.as_view(), name='subscribers'),
]

iqCP/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^list/$', views.UsersList.as_view(), name='list'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.UserDetail.as_view(), name='detail')
]

iqCP/promo/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

from users.models import Users

class PromoCodes(models.Model):
    code_id = models.AutoField(primary_key=True)
    code = models.CharField(unique=True, max_length=10)
    creation_time = models.DateTimeField(blank=True, null=True)
    used_time = models.DateTimeField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    subscriber = models.ForeignKey('SiteSubscribers', models.DO_NOTHING, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'promo_codes'

    def get_absolute_url(self):
        return reverse('promo:promo_code', kwargs={'pk': self.pk})


class UsersPromo(models.Model):
    user = models.ForeignKey(Users, models.DO_NOTHING)
    code = models.ForeignKey(PromoCodes, models.CASCADE)

    class Meta:
        managed = False
        db_table = 'users_promo'


class SiteSubscribers(models.Model):
    subscriber_id = models.AutoField(primary_key=True)
    email = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    second_name = models.CharField(max_length=100, blank=True, null=True)
    ip = models.BigIntegerField(blank=True, null=True)
    time = models.DateTimeField(blank=True, null=True)
    job = models.CharField(max_length=1000, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'site_subscribers'

iqCP/promo/forms.py
from django import forms

from accounts.models import Profile

#форма редактирования promo codes detail
class PromoCodeDetailForm(forms.Form):
    comment = forms.CharField(label='Комментарий')

#форма приглашения
class SendInviteForm(forms.Form):
    sender = forms.ModelChoiceField(queryset=Profile.objects.all(), label='От', required=True)
    recipient = forms.CharField(label='Email получателя', required=True)
    name = forms.CharField(label='Имя получателя',required=False)
    promo_code = forms.CharField(label='Промо-код', required=False)

iqCP/promo/views.py
import os
from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail, get_connection
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, FormMixin
from django import forms
from django.db.models import F, Value, Count
from django.db.models.functions import Concat

from smtplib import SMTPAuthenticationError, SMTPException


from django.http import HttpResponseRedirect, HttpResponse


from .helpers import generate_promo, InviteEmailMessage
from .models import PromoCodes, SiteSubscribers
from accounts.models import Profile
from .forms import *

#форма редактирования promo codes detail
class PromoCodeDetailForm(forms.Form):
    comment = forms.CharField(label='Комментарий')

class ListPromoCodes(generic.ListView):
    model = PromoCodes
    template_name = 'promo/list_promo_codes.html'
    context_object_name = 'promo_codes_list'

    def get_queryset(self):
        return PromoCodes.objects.order_by('pk').all()


class PromoCodesListView(LoginRequiredMixin, ListView):

    template_name = 'promo/list_promo_codes.html'
    context_object_name = 'promo_codes'
    queryset = PromoCodes.objects.order_by('pk')\
        .select_related('subscriber')\
        .prefetch_related('userspromo_set__user__userprofile_set') \
        .annotate(user_id=F('userspromo__user__user_id'))\
        .annotate(profile_first_name=F('userspromo__user__userprofile__profile_first_name')) \
        .annotate(profile_second_name=F('userspromo__user__userprofile__profile_second_name')) \
        .all()

    paginate_by = 25

    def get_queryset(self):
        return self.queryset


class PromoCodeDetailView(LoginRequiredMixin, UpdateView):
    model = PromoCodes
    queryset = PromoCodes.objects
    context_object_name = 'promo_code'
    template_name = 'promo/promo_code_detail.html'

    fields = ['comment', ]


class PromoCodeDelete(LoginRequiredMixin, DeleteView):
    model = PromoCodes
    success_url = reverse_lazy('promo:promo_codes')
    http_method_names = ['post', ]


@login_required()
def promoCodeDetail(request, id):
    try:
        promo_code = PromoCodes.objects.get(pk=id)
    except:
        promo_code = None
    form = None
    if promo_code:
        if request.method == 'POST':
            form = PromoCodeDetailForm(request.POST)
            if form.is_valid():
                promo_code.comment = form.cleaned_data['comment']
                promo_code.save()
                return render(request, 'promo/promo_code_detail_success.html', {
                    'promo_code': promo_code,
                    'back_url': request.META.get('HTTP_REFERER')
                })
        else:
            form = PromoCodeDetailForm(initial={'comment': promo_code.comment})
    return render(request, 'promo/promo_code_detail.html', {'promo_code': promo_code, 'form': form})


@login_required()
def deletePromoCode(request, id):
    try:
        promo_code = PromoCodes.objects.get(pk=id)
    except:
        promo_code = None
        return HttpResponseRedirect(reverse('promo:promo_codes'))
    if request.method == 'POST':
        is_del = promo_code.delete()
        if is_del[0] == 1:
            return render(request, 'promo/promo_code_deleted.html', {'promo_code': promo_code})
        else:
            return render(request, 'promo/promo_code_deleted.html', {'error': True})
    else:
        return render(request, 'promo/promo_code_delete.html', {'promo_code': promo_code})


@login_required()
def invite_view(request, promo_code='', first_name='', email='', subscriber_id=None):
    profile = Profile.objects.filter(user=request.user)
    if request.method == 'POST':
        form = SendInviteForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['promo_code']:
                promo_c = form.cleaned_data['promo_code']
            else:
                promo_c = generate_promo(comment=form.cleaned_data['recipient']+','+form.cleaned_data['name'])
            if not promo_c:
                return HttpResponse('error in promo code!')
            try:
                sender = form.cleaned_data['sender']
                with get_connection(
                        host=sender.smtp_server,
                        port=sender.smtp_port,
                        username=sender.email,
                        password=sender.email_password,
                        use_ssl=(True if sender.secure_type == 1 else False)
                ) as connection:
                    email_instance = InviteEmailMessage(template_params={
                                                            'promo_code': promo_c,
                                                            'name': form.cleaned_data['name']
                                                            },
                                                        from_email=sender.email,
                                                        to=[form.cleaned_data['recipient'],],
                                                        connection=connection,
                    )
                    emails = email_instance.send()
                    if emails > 0:
                        if subscriber_id:
                            promo_obj = PromoCodes.objects.get(code=promo_c)
                            promo_obj.subscriber_id = subscriber_id
                            promo_obj.save()
                        return render(request, 'promo/invited.html')
                    else:
                        return HttpResponse('inviting error!')
            except SMTPAuthenticationError:
                return HttpResponse('authentication error!')
            except SMTPException:
                return HttpResponse('SMTP error!')
    else:
        if subscriber_id:
            try:
                subscriber = SiteSubscribers.objects.get(subscriber_id=subscriber_id)
                first_name = subscriber.first_name
                email = subscriber.email
            except:
                pass
        print('e',first_name,email)
        form = SendInviteForm(initial={
            'promo_code': promo_code,
            'name': first_name,
            'recipient': email,
        })
    preview_template = InviteEmailMessage.get_template({'preview': True})
    return render(request, 'promo/invite_view.html',
                  {'form': form, 'template': preview_template,
                   'promo_code': promo_code, 'first_name':first_name,
                   'email': email})


class SubscribersViewForm(forms.Form):
    search = forms.CharField(label='Поиск',
                             required=False,
                             initial='')



class SubscribersView(LoginRequiredMixin, ListView, FormMixin):

    queryset = SiteSubscribers.objects.order_by('-time').prefetch_related('promocodes_set').all()
    template_name = 'promo/subscribers.html'
    context_object_name = 'subscribers'
    paginate_by = 25

    form_class = SubscribersViewForm

    def get_queryset(self):
        subscribers = self.queryset

        form = self.get_form()

        if form.is_valid():
            search = form.cleaned_data.get('search')
            if search:
                subscribers = subscribers.annotate(fullname=Concat(F('first_name'), Value(' '), F('second_name')))\
                    .filter(fullname__icontains=search)

        return subscribers

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.GET:
            kwargs.update({'data': self.request.GET})
        return kwargs

iqCP/promo/templates/promo/invite_view.html
{% extends "base.html" %}
{% block content %}
    <div style="width: 100%">
    <div style="display: inline-block; vertical-align: top; width: 30%">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Пригласить</button>
        </form>
    </div>
    <div style="display: inline-block; vertical-align: top; width: 50%">
        {{template}}
    </div>
    </div>
{% endblock %}

iqCP/promo/templates/promo/invited.html
user invited!

iqCP/promo/templates/promo/list_promo_codes.html
{% extends "base.html" %}
{% block title %} promo codes {% endblock %}

{% block content %}
<div class="row"><div class="col-xs-12">
        <h2>Промокоды
        <a class="btn btn-default pull-right" href="{% url 'promo:invite' promo_code='' %}">
            Пригласить <span class="fa fa-user-plus"></span>
        </a></h2>
    </div></div>
{% if promo_codes %}
    <div class="row"><div class="col-xs-12">
    <table class="table table-hover">
        <tr>
            <td>Промо код</td>
            <td>Когда создан</td>
            <td>Когда активирован</td>
            <td>Комментарий</td>
            <td>Подписчик</td>
            <td></td>
        </tr>
        {% for code in promo_codes %}
            <tr>
                <td>{{code.code}}</td>
                <td>{{code.creation_time}}</td>
                <td>{{code.used_time}}</td>
                <td>{{code.comment}}</td>
                <td>
                    {% if code.userspromo_set.all %}
                        <a href="{% url 'users:detail' code.user_id %}">
                            {{code.profile_first_name}}
                            {{code.profile_second_name}}
                        </a>
                    {% else %}
                        {{code.subscriber.first_name}} {{code.subscriber.second_name}}
                    {% endif %}
                </td>
                <td><a href="{% url 'promo:promo_code' code.code_id %}">ред.<a/></td>
            </tr>
        {% endfor %}
    </table>
    </div></div>
{% else %}
    no promo codes
{% endif %}
<div class="row"><div class="col-xs-12">
<ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <a href="?page={{page_obj.previous_page_number }}"><span>&laquo;</span></a>
            </li>
        {% endif %}
        {% for page in paginator.page_range  %}
            <li
                {% if page_obj.number == page %}
                class="active"
                {% endif %}
            >
                <a href="?page={{page}}">{{page}}</a>
            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li>
                <a href="?page={{page_obj.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
            </li>
        {% endif %}
</ul>
</div></div>
{% endblock content%}

iqCP/promo/templates/promo/promo_code_delete.html
{% extends "base.html" %}
{% block content %}
{% if promo_code%}
    <form action="{% url 'promo:delete_promo' id=promo_code.code_id %}" method="POST">
        {% csrf_token %}
        Удалить промо-код {{promo_code.code}}?
        <button type="submit">Удалить</button>
    </form>
{% else %}
    Промо-кода не существует
{% endif %}
{% endblock %}

iqCP/promo/templates/promo/promo_code_deleted.html
{% extends "base.html" %}
{% block content %}
    {% if not error %}
        Промо-код {{promo_code.code}} удален
    {% else %}
        Произошла ошибка при удалении промо-кода {{promo_code.code}}
    {% endif %}
{% endblock %}

iqCP/promo/templates/promo/promo_code_detail.html
{% extends "base.html" %}
{% block content %}
{% if not promo_code %}
    <p>no selected promo</p>
{% else %}
    <div class="row">
        <div class="col-xs-12 text-right">
            <form action="{% url 'promo:delete_promo' promo_code.code_id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="удалить">
            </form>
        </div>
    </div>

    <form action="{% url 'promo:promo_code' promo_code.code_id %}" method="POST">
        {% csrf_token %}
        <label>Промо код: </label>{{promo_code.code}}
        <br>
        <label>Когда создан: </label>{{promo_code.creation_time}}<br>
        <label>Когда активирован: </label>{{promo_code.used_time}}<br>
        {{form}}<br>
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'promo:invite' promo_code=promo_code.code %}">invite</a>
{% endif %}
{% endblock content %}

iqCP/promo/templates/promo/promo_code_detail_success.html
{% if promo_code %}
    изменения сохранены
    <a
        {% if back_url %} href="{{back_url}}"
        {% else %} href="{% url 'promo_codes' %}" {% endif %}
    >
        назад
    </a>
{% endif %}

iqCP/promo/templates/promo/subscribers.html
{% extends "base.html" %}
{% block title %} subscribers {% endblock %}

{% block content %}
<h2>Подписчики</h2>
<form method="GET" action=".">
<div class="row">
    <div class="col-xs-12">
         <div class="input-group">
                <input name="search"
                       class="form-control"
                       type="text"
                       placeholder="фамилия, имя"
                       value="{{form.search.value}}"
                >
                <span class="input-group-btn">
                    <input class="btn btn-default" type="submit" value="Поиск">
                </span>
            </div>
    </div>
</div>
</form>
<div class="row"><div class="col-xs-12">
    {% if subscribers %}
    <table class="table table-hover">
        <tr>
            <td>Email</td>
            <td>Имя</td>
            <td>Фамилия</td>
            <td>Время регистрации</td>
            <td>Сфера</td>
            <td>Приглашение</td>
            <td></td>
        </tr>
        {% for sub in subscribers %}
            <tr>
                <td>{{sub.email}}</td>
                <td>{{sub.first_name}}</td>
                <td>{{sub.second_name}}</td>
                <td>{{sub.time}}</td>
                <td>{{sub.job}}</td>
                <td>
                    {% if not sub.promocodes_set.all %}
                        нет
                    {% endif %}
                    {% for code in sub.promocodes_set.all %}
                        <a href="{% url 'promo:promo_code' code.code_id %}">{{code.code}}</a><br>
                    {% endfor %}
                </td>
                {# <td><a href="{% url 'promo:invite' email=sub.email first_name=sub.first_name %}">invite<a/></td> #}
                <td><a href="{% url 'promo:invite' subscriber_id=sub.subscriber_id %}">Пригласить<a/></td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
        no subscribers
    {% endif %}
</div></div>
<div class="row"><div class="col-xs-12">
<ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <a href="?page={{page_obj.previous_page_number}}&search={{form.search.value}}"><span>&laquo;</span></a>
            </li>
        {% endif %}
        {% for page in paginator.page_range  %}
            <li
                {% if page_obj.number == page %}
                class="active"
                {% endif %}
            >
                <a href="?page={{page}}&search={{form.search.value}}">{{page}}</a>
            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li>
                <a href="?page={{page_obj.next_page_number}}&search={{form.search.value}}"><span aria-hidden="true">&raquo;</span></a>
            </li>
        {% endif %}
</ul>
</div></div>
{% endblock content%}